version: '2'
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "4200:4200"
      - "80:4200"
